# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
