# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20190603_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(default='neigh', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
