# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20190603_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
