# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_profile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
