# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
