# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Food', 'Food'), ('Furniture', 'Furniture')], max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('descripion', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='image/')),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='neighbourhood.Neighbourhood')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_products', to='neighbourhood.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
