# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0011_auto_20190607_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripion',
            new_name='description',
        ),
    ]
